---
title: "ERHS 535 Homework 5"
author: "Sherry WeMott"
date: "11/21/2019"
output:
  pdf_document: default
  html_document: default
---

```{r, include = FALSE}
# load packages
library(tidyverse)
library(tigris)
library(sf)
library(ggthemes)
```


```{r, results = 'hide'}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)

# read in data
denver <- read_csv("../data/homicide-data.csv") %>% 
  filter(city == "Denver") %>% 
  select(lat, lon, disposition, victim_race)
```


```{r}
# filter by race
denver_race <- denver %>% 
  group_by(victim_race) %>% 
  mutate(count = n()) %>% 
  arrange(desc(count)) %>% 
  ungroup() %>% 
  filter(victim_race == c("Black", "White", "Hispanic"))  
```


```{r, results = 'hide'}
# create zip code map
denver_zip <- zctas(cb = TRUE, starts_with = 
                      c("802"), class = "sf")
``` 

```{r}
# categorize into solved and unsolved
denver_disp <- denver_race %>% 
  mutate(disposition = factor(disposition, levels = c("Closed without arrest", 
                                                      "Closed by arrest", 
                                                      "Open/No arrest"),
                              labels = c("solved", "solved", "unsolved")))
``` 


```{r}
# create dataframe of disposition status with geocode
denver_crs <- denver_disp %>% 
  filter(!is.na(lat)) %>% 
  st_as_sf(coords = c("lon", "lat")) %>% 
  st_set_crs(4269)
```


```{r, fig.width = 7, fig.height = 8, dpi = 300}

# create plot of homicides overlayed on denver map, faceted by race
zip_map <- ggplot() +
  geom_sf(data = denver_zip, color = "lightgray") +
  geom_sf(data = denver_crs, aes(color = factor(victim_race)), 
          show.legend = 'point') +
  facet_wrap(~disposition, ncol =1) +
  ggtitle("Homicide cases in Denver, CO 2007-2017", subtitle = "(map shows zipcode boundaries)") +
  labs(x = "Longitude", y = "Latitude") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")) +
  labs(colour = "Victim Race") 
  
zip_map
```

